---
title: "p8105_hw6_yl5227"
author: "Jennifer Li"
date: "2023-12-02"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1

data cleaning

```{r}
homi_df = 
  read_csv("data/homicide-data.csv") |> 
  mutate(
    city_state = str_c(city, ", ", state),
    solved = !disposition %in% c("Closed without arrest","Open/No arrest"),
    victim_age = as.numeric(victim_age)
  ) |> 
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("Black", "White")
  ) |> 
  select(uid,city_state,solved,victim_race, victim_age, victim_sex) |> 
  na.omit()
```

Do the logistic regression on `Baltimore, MD`.

```{r}
logi_fit = 
  homi_df |> 
  filter(city_state == "Baltimore, MD") |> 
  glm(solved~ victim_race + victim_age + victim_sex, data = _, family = "binomial")

logi_fit |> 
  broom::tidy() |> 
  filter(term == "victim_sexMale") |> 
  mutate(
    odds_ratio = exp(estimate),
    conf_low = exp(estimate  - 1.96 * std.error),
    conf_high = exp(estimate + 1.96 * std.error)
  )  |> 
  select(term, odds_ratio, conf_low, conf_high)
```

Iterate over other cities with logistic regression.

```{r}
logi_fit =
  homi_df |> 
  nest(data = c(uid, solved, victim_age, victim_race, victim_sex)) |> 
  mutate(
    model = map(.x = data, ~glm(solved ~ victim_race + victim_age + victim_sex, data = .x, family = "binomial")),
    estimate = map(.x  = model, ~filter(broom::tidy(.x), term == "victim_sexMale"))
  ) |> 
  unnest(estimate) |> 
  mutate(
    odds_ratio = exp(estimate),
    conf_low = exp(estimate  - 1.96 * std.error),
    conf_high = exp(estimate + 1.96 * std.error)
  )  |> 
  select(city_state, odds_ratio, conf_low, conf_high)

logi_fit
```

Finally, plot the odds ratio between cities.

```{r}
logi_fit |> 
  mutate(
    city_state = fct_reorder(city_state, -odds_ratio)
  ) |> 
  ggplot(aes(x = odds_ratio, y = city_state)) +
  geom_point() +
  geom_vline(aes(xintercept = 1), color = "red") +
  geom_errorbar(aes(xmin = conf_low, xmax = conf_high)) +
  labs(title = "Odds ratio of solved cases between male and female victims")
```

Thus, in most cities, after adjusting for race and age, cases with male victims have more odds to be unsolved.

# Problem 2

Use code provided to download `Central Park` weather data.

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

